/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-10-30 15:57:41 UTC)
 * on 2013-11-13 at 20:45:23 UTC 
 * Modify at your own risk.
 */

package com.appspot.sortonsevents.clientdata.model;

/**
 * Model definition for FbPage.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the clientdata. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class FbPage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String pageId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String pageUrl;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public FbPage setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPageId() {
    return pageId;
  }

  /**
   * @param pageId pageId or {@code null} for none
   */
  public FbPage setPageId(java.lang.String pageId) {
    this.pageId = pageId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPageUrl() {
    return pageUrl;
  }

  /**
   * @param pageUrl pageUrl or {@code null} for none
   */
  public FbPage setPageUrl(java.lang.String pageUrl) {
    this.pageUrl = pageUrl;
    return this;
  }

  @Override
  public FbPage set(String fieldName, Object value) {
    return (FbPage) super.set(fieldName, value);
  }

  @Override
  public FbPage clone() {
    return (FbPage) super.clone();
  }

}
